spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/develop/h2/hem_user
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

  test:
    database:
      connection: H2

logging:
  level:
    org.hibernate.SQL: debug

# hem property
hem:
  token:
    expiration: 1000